name: Run Tests 

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupération du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Étape 3 : Installation des dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Lancer les tests
      - name: Run Tests
        run: npm test

      # Étape 5 : 
      - name: Upload Test Results 
         if: always()
         uses: actions/upload-artifact@v3
         with:
            name: test-results
            path:./test-results
       
        
